=== caraya/xml-workflow/xsd/book-schema-draft.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <!-- Simple types to use in the content -->
    <xs:simpleType name="string255">
        <xs:annotation>
            <xs:documentation>Defines a string of no more than 255 characters</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:maxLength value="255"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="isbn">
        <xs:annotation>
            <xs:documentation>Defines a regular expression to match an ISBN number. Regex needs to be refined</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:unsignedLong">
            <xs:totalDigits value="10"/>
            <xs:pattern value="\d{10}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="align">
        <xs:annotation>
            <xs:documentation>Attribute ennumeration for elements that can be aligned</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="left"/>
            <xs:enumeration value="center"/>
            <xs:enumeration value="right"/>
            <xs:enumeration value="justify"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:attributeGroup name="genericPropertiesGroup">
        <xs:attribute name="id" type="xs:ID" use="optional">
            <xs:annotation>
                <xs:documentation>ID for the paragraph if any</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="class" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>Class for the paragraph if any</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:attributeGroup> 

    <!-- complex types to create groups of similar person items -->
    
    <xs:complexType name="person">
        <xs:annotation>
            <xs:documentation>Generic element to denote an individual involved in creating the book</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="first-name" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
    
    <xs:complexType name="authors">
        <xs:annotation>
            <xs:documentation>Wrapper to get more than one author</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="author" type="person"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="editors">
        <xs:annotation>
            <xs:documentation>extension to person to indicate editor and his/her role</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="person">
                <xs:sequence>
                    <xs:element name="type" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="otherRoles">
        <xs:annotation>
            <xs:documentation>extension to person to accomodate roles other than author and editor</xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="person">
                <xs:sequence>
                    <xs:element name="role" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Elements inside section -->
    <xs:element name="link">
        <xs:annotation>
            <xs:documentation>links... </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attributeGroup ref="genericPropertiesGroup"/>
            <xs:attribute name="href" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>Link destination</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="label" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>Text provided for accessibility</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="image">
        <xs:annotation>
            <xs:documentation>image and image-related attributes</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attributeGroup ref="genericPropertiesGroup"/>
            <xs:attribute name="src" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Source for the image. We may want to create a restriction to account for both local and remote addresses
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="height" type="xs:integer" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        Height for the image expressed as an integer
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="width" type="xs:integer" use="optional">
                <xs:annotation>
                    <xs:documentation>
                        Width for the image expressed as an integer
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>            
            <xs:attribute name="alt" type="string255" use="required">
                <xs:annotation>
                    <xs:documentation>
                        Alternate text contstained to 255 characters
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="align" type="align" use="optional" default="left">
                <xs:annotation>
                    <xs:documentation>
                        Optional alignment
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            
        </xs:complexType>
    </xs:element>
    
    <xs:element name="para">
        <xs:annotation>
            <xs:documentation>Para is the essential text content element. It'll get hairy because we
                have a lot of possible attributes we can use on it</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence>
                <!-- 
                    Style Elements. 
                    
                    We use strong and emphasis rather than bold and italics
                    to try and stay in synch with HTML and HTML5. We may add additional tags
                    later in the process.
                -->
                <xs:element name="strong" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="emphasis" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="underline" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="strike" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <!-- 
                    Organization Elements 
                -->
                <xs:element name="span" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="link" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>
                            Links should happen inside paragraphs and it's an optional element inside.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attributeGroup ref="genericPropertiesGroup"/>
        </xs:complexType>
    </xs:element>

    <!-- Metadata element -->
    <xs:element name="metadata">
        <xs:annotation>
            <xs:documentation>Metadata section of the content. Still debating whether to move it inside section or leave it as a separate part.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:annotation>
                    <xs:documentation>Metadata sequence using ISBN, Edition, Title, Authors, Editors and Other Roles defined using simple and complex type definitions defined earlier</xs:documentation>
                </xs:annotation>
                <xs:element name="isbn" type="isbn"/>
                <xs:element name="edition" type="xs:integer"/>
                <xs:element name="title" type="string255"/>
                <xs:element name="authors" type="authors" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="editors" type="editors" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="otherRoles" type="otherRoles" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="section">
        <xs:annotation>
            <xs:documentation>section structure</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:annotation>
                    <xs:documentation>At least one paragraph </xs:documentation>
                </xs:annotation>
                <xs:element ref="para" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attributeGroup ref="genericPropertiesGroup"/>
            <xs:attribute name="type" type="xs:string" use="optional" default="chapter">
                <xs:annotation>
                    <xs:documentation>
                        The type or role for the paragraph asn in data-role or epub:type
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="book">
        <xs:annotation>
            <xs:documentation>The main book element and it's children</xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:annotation>
                <xs:documentation>A sequence of one metadat section followed by 1 or more sections</xs:documentation>
            </xs:annotation>
            <xs:sequence>
                <xs:element ref="metadata" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="section" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attributeGroup ref="genericPropertiesGroup"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== caraya/xml-workflow/docs-min.xml
<?xml version="1.0" encoding="UTF-8" ?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/book-schema-draft.xsd">
  <metadata>
    <title>XML workflow documentation</title>

    <authors>
      <author>
        <first-name>Carlos</first-name>
        <surname>Araya</surname>
      </author>
    </authors>
  </metadata>
  <toc />
  <section type="chapter">
    <title>Converting to ePub</title>

    <blockquote>
      <para>This chapter is a draft! This style sheet is under development</para>
    </blockquote>

    <para>Perhaps the most ambitious part of the proof of concept is to convert the XML content to an ePub book that would pass epubcheck validation. To accomplish this we'll create another customization layer to acommodate the special syntax and additional content needed to create the ePub 3 package.</para>

    <para>This is more complicated than the creation of the single file for generating PDF. The epub specification is more complex and requires a lot more auxiliary files and directories with very specific formatting. I wonder if some of them need to be XML files at all.</para>

    <para>Take the <emphasis>package.opf</emphasis>, for example. As portable as XML is and as many XML parsers are there in the wild, it would work much better if we do the same code in JSON, YAML, or other similar formats.</para>

    <para />
  </section>
</book>

=== caraya/xml-workflow/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="xsd/book-schema-draft.xsd">
    <metadata>
        <isbn>1234567890</isbn>
        <edition>0</edition>
        <title>title0</title>
        <author>
            <first-name>first-name0</first-name>
            <surname>surname0</surname>
        </author>
        <author>
            <first-name>first-name1</first-name>
            <surname>surname1</surname>
        </author>
    </metadata>
    <section>
        <para>
        </para>
        <para>
        </para>
    </section>
    <section>
        <para>
        </para>
        <para>
        </para>
    </section>
</book>

=== caraya/xml-workflow/book1.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/carlos/code/xml-workflow/xsd/book-schema-draft.xsd">
    <metadata>
        <isbn>5012097465</isbn>
        <edition>0</edition>
        <title>title0</title>
        <authors>
            <author>
                <first-name>first-name0</first-name>
                <surname>surname0</surname>
            </author>
        </authors>
        <authors>
            <author>
                <first-name>first-name1</first-name>
                <surname>surname1</surname>
            </author>
        </authors>
    </metadata>
    <section>
        <title>title1</title>
        <para/>
        <para/>
    </section>
    <section>
        <title>title2</title>
        <para/>
        <para/>
    </section>
</book>
